name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.0"
          enable-cache: true
          cache-dependency-glob:  |
            pyproject.toml

      - name: Install python deps
        run: |
          uv pip install --system -e ".[test]"

      - name: Python Tests
        run: pytest